// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1XwDrTsUpnC7u08XPRK8QqpnZB5U-KD4',
    appId: '1:58730508853:web:d327fedd4e50f7262ff77c',
    messagingSenderId: '58730508853',
    projectId: 'mhtechin-635ac',
    authDomain: 'mhtechin-635ac.firebaseapp.com',
    storageBucket: 'mhtechin-635ac.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEYL6_yL5zw1eTC9wEav2tMSZA9nBXclI',
    appId: '1:58730508853:android:7545595065708ac52ff77c',
    messagingSenderId: '58730508853',
    projectId: 'mhtechin-635ac',
    storageBucket: 'mhtechin-635ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4rdJCnzaErkCiVtV6qB-hy1lske9ErCw',
    appId: '1:58730508853:ios:b3645fab865d90142ff77c',
    messagingSenderId: '58730508853',
    projectId: 'mhtechin-635ac',
    storageBucket: 'mhtechin-635ac.appspot.com',
    iosBundleId: 'com.example.otpVerify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4rdJCnzaErkCiVtV6qB-hy1lske9ErCw',
    appId: '1:58730508853:ios:b3645fab865d90142ff77c',
    messagingSenderId: '58730508853',
    projectId: 'mhtechin-635ac',
    storageBucket: 'mhtechin-635ac.appspot.com',
    iosBundleId: 'com.example.otpVerify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1XwDrTsUpnC7u08XPRK8QqpnZB5U-KD4',
    appId: '1:58730508853:web:5b8e668932c620582ff77c',
    messagingSenderId: '58730508853',
    projectId: 'mhtechin-635ac',
    authDomain: 'mhtechin-635ac.firebaseapp.com',
    storageBucket: 'mhtechin-635ac.appspot.com',
  );
}
